---
- name: Remove etcd_hpe service
  hosts: all
  become: yes
  tasks:
    - name: Remove etcd_hpe service 
      include: remove_etcd_service.yml
      ignore_errors: yes

- name: Uninstall HPE 3PAR Volume Driver
  hosts: all
  become: yes

  tasks:
    - name: load plugin settings
      include_vars: '../properties/plugin_configuration_properties.yml'

    - name: Remove 3PAR Volume Plugin container from Docker
      include: remove_3par_docker_container.yml
      ignore_errors: yes

    - name: Reset multipath
      include: remove_multipath.yml

