- hosts: all

  environment:
    http_proxy: "http://web-proxy.in.hpecorp.net:8080"
    https_proxy: "http://web-proxy.in.hpecorp.net:8080"

  tasks:
  - name: load plugin settings
    include_vars: 'properties/plugin_configuration_properties.yml'

  - name: get the iscsi ports
    local_action: shell /usr/bin/sshpass -p {{ INVENTORY[item]['hpe3par_password'] }} ssh -oStrictHostKeyChecking=no {{ INVENTORY[item]['hpe3par_username'] }}@{{ INVENTORY[item]['hpe3par_ip'] }} "showport -iscsi" | grep ready | awk '{print $3}'
    with_items: "{{ INVENTORY.keys() }}"
    register: ports
    
  - name: Creates HPE Docker plugin directory
    file:
      path: /etc/hpedockerplugin
      state: directory
      mode: 0644
      recurse: yes
    become: yes

  - name: Populate hpe.conf
    ini_file:
      path: /etc/hpedockerplugin/hpe1.conf
      section: "{{ item[0] }}"
      option: "{{ item[1]['option'] }}"
      value: "{{ INVENTORY[item[0]][item[1].value] }}"
      no_extra_spaces: true
    with_nested:
      - "{{ INVENTORY.keys()}}"
      - [{ option: 'ssh_hosts_key_file', value: 'ssh_hosts_key_file' }, { option: 'host_etcd_port_number', value: 'host_etcd_port_number' }, { option: 'logging', value: 'logging' }, { option: 'hpe3par_debug', value: 'hpe3par_debug' }, { option: 'suppress_requests_ssl_warning', value: 'suppress_requests_ssl_warning' }, { option: 'hpe3par_username', value: 'hpe3par_username' }, { option: 'hpe3par_password', value: 'hpe3par_password' }, { option: 'hpe3par_cpg', value: 'hpe3par_cpg' }, { option: 'hpe3par_snapcpg', value: 'hpe3par_snapcpg' }, { option: 'hpe3par_iscsi_chap_enabled', value: 'hpe3par_iscsi_chap_enabled' }, { option: 'use_multipath', value: 'use_multipath' }, { option: 'enforce_multipath', value: 'enforce_multipath' }, { option: 'hpedockerplugin_driver', value: 'hpedockerplugin_driver' }, { option: 'san_ip', value: 'hpe3par_ip' }, { option: 'san_ip', value: 'hpe3par_ip' }, { option: 'san_login', value: 'hpe3par_username' }, { option: 'san_password', value: 'hpe3par_password' }]
    become: yes
      
  - name: Populate hpe.conf
    ini_file:
      path: /etc/hpedockerplugin/hpe1.conf
      section: "{{ item[0] }}"
      option: "{{ item[1]['option'] }}"
      value: "{{ item[1]['value'] }}"
      no_extra_spaces: true
    with_nested:
      - "{{ INVENTORY.keys()}}"
      - [{ option: 'host_etcd_ip_address', value: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}" }]
    become: yes
    
  - name: Populate hpe.conf
    ini_file:
      path: /etc/hpedockerplugin/hpe1.conf
      section: "{{ item[0] }}"
      option: "{{ item[1]['option'] }}"
      value: "{{ 'https://' + INVENTORY[item[0]][item[1].value] + ':8080/api/v1' }}"
      no_extra_spaces: true
    with_nested:
      - "{{ INVENTORY.keys()}}"
      - [{ option: 'hpe3par_api_url', value: 'hpe3par_ip' }]
    become: yes
    
  - name: Populate iscsi IPs in hpe.conf
    ini_file:
      path: /etc/hpedockerplugin/hpe1.conf
      section: "{{ item[0] }}"
      option: 'hpe3par_iscsi_ips'
      value: "{{ ','.join(item[1]['stdout_lines']) }}"
      no_extra_spaces: true
    with_nested:
      - "{{ INVENTORY.keys()}}"
      - "{{ ports['results'] }}"
    become: yes


