---
  - name: load etcd settings
    include_vars: '../properties/etcd_cluster_properties.yml'

  - name: Create FlexVolume driver directory
    file:
      path: "{{ item }}"
      state: directory
      mode: 0644
      recurse: yes
    with_items:
      - "{{ driver_path }}"
      - /etc/kubernetes/

  - local_action: file path=/tmp/config state=absent

  - name: Check that the config file exists
    stat:
      path: /root/.kube/config
    register: config_stat_result

  - name: Check that the admin.conf file exists
    stat:
      path: /etc/kubernetes/admin.conf
    register: admin_stat_result
    when: inventory_hostname in groups['masters']

  - fail:
      msg: "The config file does not exist either at /root/.kube/config or /etc/kubernetes/admin.conf"
    when: inventory_hostname in groups['masters'] and config_stat_result.stat.exists == False and admin_stat_result.stat.exists == False

  - name: Copy over the kube config file into /tmp
    fetch:
      src: /root/.kube/config
      dest: /tmp/config
      flat: yes
    when: inventory_hostname in groups['masters'] and config_stat_result.stat.exists

  - name: Copy over the admin.conf file into /tmp
    fetch:
      src:  /etc/kubernetes/admin.conf
      dest: /tmp/config
      flat: yes
    when: inventory_hostname in groups['masters'] and admin_stat_result.stat.exists

  - name: Verify /etc/kubernetes/admin.conf exists
    copy:
      src: /tmp/config
      dest: /etc/kubernetes/admin.conf
      owner: "root"
      mode: 0755
  
