---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: doryd
spec:
  updateStrategy:
     type: RollingUpdate
  template:
    metadata:
      namespace: kube-system
      labels:
        daemon: dory-daemon
      name: doryd
    spec:
      restartPolicy: Always
      tolerations:
       -
          effect: NoSchedule
          operator: Exists
      containers:
        -
          image: hpestorage/hpe3par_doryd_sles:1.0
          imagePullPolicy: Always
          name: dory
          volumeMounts:
             - name: k8s
               mountPath: /etc/kubernetes
             - name: config
               mountPath: /root/.kube/config
             - name: flexvolumedriver
               mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
             - name: dockersocket
               mountPath: /run/docker/plugins/
      volumes:
        - name: k8s
          hostPath:
             path: /etc/kubernetes/
        - name: config
          hostPath:
             path: /root/.kube/config
        - name: flexvolumedriver
          hostPath:
             path: /var/lib/kubelet/volumeplugins
        - name: dockersocket
          hostPath:
              path: /run/docker/plugins/
