---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: doryd
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: doryd
subjects:
  - kind: ServiceAccount
    name: doryd
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: doryd
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: doryd
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-storage-controller-doryd
  namespace: kube-system
  labels:
    app: doryd
spec:
  strategy:
     type: RollingUpdate
  template:
    metadata:
      labels:
        daemon: kube-storage-controller-daemon
      name: kube-storage-controller
    spec:
      restartPolicy: Always
      serviceAccountName: doryd
      containers:
        -
          image: hpestorage/hpe3par_doryd_openshift:1.0
          imagePullPolicy: Always
          name: kube-storage-controller
          volumeMounts:
            - name: flexvolumedriver
              mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
              readOnly: true
            - name: dockersocket
              mountPath: /run/docker/plugins/
      volumes:
        - name: flexvolumedriver
          hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
        - name: dockersocket
          hostPath:
            path: /run/docker/plugins/
