#!/bin/bash

#TODO dump the EULA using more or less

while true; do
    read -p "Proceed with installation of dory/doryd binaries ? " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done

installDir=/usr/libexec/kubernetes/kubelet-plugins/volume/exec/hpe.com~hpe/

if [ -d ${installDir} ]
then
    echo "Upgrading flexvolumedriver."
else
    echo "Installing flexvolumedriver."
    mkdir -p $installDir
fi

mv ./* "${installDir}"

rm ${installDir}/install

exit 0

